name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore './src/CrudeObservatory/'
    - name: Build
      run: dotnet build './src/CrudeObservatory/' --no-restore
    - name: Test
      run: dotnet test './src/CrudeObservatory/' --no-build --verbosity normal

     #Publish CLI
      # - name: Define MSBuild properties
      #   run: echo "MSBUILD_PROPS=-p:PublishSingleFile=true -p:PublishTrimmed=true -p:TrimMode=link -p:DebuggerSupport=false -p:EnableUnsafeBinaryFormatterSerialization=false -p:EnableUnsafeUTF7Encoding=false -p:InvariantGlobalization=true" >> $GITHUB_ENV
    - name: Publish CLI framework-dependent
      run: |
        dotnet publish './src/CrudeObservatory/CrudeObservatory/' -c Release

    #Upload CLI
    - name: Upload CLI artifacts for Windows framework-dependent
      uses: actions/upload-artifact@v2
      with:
        name: crudeobservatory-${{ github.sha }}-windows
        path: src/CrudeObservatory/CrudeObservatory/bin/Release/net6.0/publish/