name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore './src/'
    - name: Build
      run: dotnet build './src/' --no-restore
    - name: Test
      run: dotnet test './src/' --no-build --verbosity normal

     #Publish CLI
      # - name: Define MSBuild properties
      #   run: echo "MSBUILD_PROPS=-p:PublishSingleFile=true -p:PublishTrimmed=true -p:TrimMode=link -p:DebuggerSupport=false -p:EnableUnsafeBinaryFormatterSerialization=false -p:EnableUnsafeUTF7Encoding=false -p:InvariantGlobalization=true" >> $GITHUB_ENV
    - name: Publish CLI framework-dependent
      run: |
        dotnet publish './src/Programs/CrudeObservatory.CLI/' -c Release

    #Upload CLI
    - name: Upload CLI artifacts for Linux framework-dependent
      if: matrix.os == 'ubuntu-20.04'
      uses: actions/upload-artifact@v2
      with:
        name: crudeobservatory-${{ github.sha }}-linux
        path: src/Programs/CrudeObservatory.CLI/bin/Release/net6.0/publish/

    - name: Upload CLI artifacts for Windows framework-dependent
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: crudeobservatory-${{ github.sha }}-windows
        path: src/Programs/CrudeObservatory.CLI/bin/Release/net6.0/publish/